name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
    strategy:
      matrix:
        node-version: ['18']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Start test server
        run: npm run start:test &
        
      - name: Wait for test server
        run: |
          echo "Waiting for test server to start..."
          until $(curl --output /dev/null --silent --head --fail http://localhost:$(grep -oP '(?<=Now listening on port )\d+' <(npm run start:test &))); do
              printf '.'
              sleep 5
          done

      - name: Run unit tests
        run: npm run test:unit

      - name: Run integration tests (Cypress)
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'http://localhost:3030'