name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]  # Change to Node.js version 18
        mongodb-version: [4.2]

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run start:test
          wait-on: 'http://localhost:3030'
          config-file: 'cypress.config.js'